/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package br.giovannicuriel.kafka.listener

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test fun testAppHasAGreeting() {
        val classUnderTest = App()
        assertNotNull(classUnderTest, "app should have a greeting")
    }
}
